spring.application.name=demo
server.shutdown=graceful

logging.file.name=logs/demo.log
logging.logback.rollingpolicy.max-file-size=100MB
logging.logback.rollingpolicy.max-history=30

# Maximum number of simultaneous connections that Tomcat will accept/handle.
server.tomcat.max-connections=100
# Minimum number of idle worker threads kept ready to handle incoming requests.
server.tomcat.threads.min-spare=5
# Maximum number of worker threads available to process requests concurrently.
server.tomcat.threads.max=20
